### ISSUE TITLE
Spanish text while app is set to English in the dashboard cash flow chart

### ISSUE THREAD

**Issue by justTOBBI** [enrique-lozano/Monekin#138] opened 2024-03-19 14:26 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When I select English as the app's main language and go to the `Cash Flow` Diagram on the Dashboard, there are Spanish categories under the bars.

<img width="540" alt="IpTWVEhrc0" src="https://github.com/enrique-lozano/Monekin/assets/47004621/9a913df5-d14a-46f2-b939-aac40192da7e">

(also note the small graphical glitch that is happening at the 1.2k bar at the very top)

### Expected Behavior

I'd expect the App to use full English translations (which I'd be happy to contribute, as well as German translations)

### Steps to Reproduce

1. Newest App Version
2. Settings -> Main Settings -> App Language -> `English`
3. Dashboard -> Cash Flow

**Comment by enrique-lozano** [comment] 2024-03-19 17:21
Hi! First of all, thank you for bringing this issue and for using Monekin. Regarding the translations, I would be really really happy to accept any PR that brings new languages to the app or that fix some texts in the current ones.

I will take a look to the chart problem in the next days also, but I'm not really convinced about this chart. The problem is that I don't know if it is useful or we should display directly the bar chart that we have in the stats section. What do you think?

Again, thanks a lot for download and test the app, it looks like it's getting more downloads recently, so I hope we can make this grow a lot in the future together.

**Comment by justTOBBI** [comment] 2024-03-19 19:08
Personally, I'd prefer the transactions of the day or past 5 transaction for a quick glance.
That could replace the Cash Flow widget imo.

Another place where the translation is missing, is when one "expandes" a view.
The text that isn't translated is 'Mostrar mas campos'

When I find some time or procrastinate on my A Level exams, I'll PR German translation. Do I need to add it somewhere that the i18n folder and autogen the file?

**Comment by enrique-lozano** [comment] 2024-03-19 19:38
Wow, lot of translations to fix. I will fix them as soon as possible (this week 100%). I will think about the charts in the dashboard also.

Regarding the new translation and broadly speaking, it's exactly what you say, but you probably also need to add the German option in the language selector. Also ensure that people with the device in German, see the app in German when they first enter the app.

Don't worry if something is missing from the PR as I will review it and add whatever is needed before merging it.

**Comment by enrique-lozano** [comment] 2024-03-19 22:55
Some translations has already benn merged to `develop` in #140

**Comment by ArturoRomanelli** [comment] 2024-03-20 13:55
Seems like also the subcategories are not loaded correctly from `default_categories.json` file, since I have categories in English and subcategories in spanish.

**Comment by enrique-lozano** [comment] 2024-10-04 10:09
Closed this as this chart no longer appears in the app dashboard since version `7.1.0`

**Closed by enrique-lozano** 2024-10-04 10:09 UTC
Labels: type: bug
