### ISSUE TITLE
Recurrent transactions will show up early

### ISSUE THREAD

**Issue by shinebrillant** [enrique-lozano/Monekin#243] opened 2024-11-10 07:56 UTC
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

Among the transaction projects, the projects for the next month and the next year will be displayed in advance.

### Expected Behavior

In the transaction items, only the transaction items of this month are displayed.

### Steps to Reproduce

Increase recurring transactions for next month and next year.

### Additional Information

![ResizedImage_2024-11-10_16-06-05_1258](https://github.com/user-attachments/assets/6e4abeb6-6b0b-4c76-b8f1-3053cf980738)

**Comment by vincius0000** [comment] 2024-11-10 18:44
Hello,

Is this the page you're writing about?

![image](https://github.com/user-attachments/assets/c622a274-9adc-45c8-9cd5-d8678974cbbf)

If yes, please notice the remark at the very bottom: "Without considering the start and end date of each recurrence".
Considering this, it might not be a bug, but rather a feature request to hide transactions that have not started their recurrence cycle.

**Comment by shinebrillant** [comment] 2024-11-10 21:14
Only this month is displayed on the transaction page.

**Comment by vincius0000** [comment] 2024-11-10 21:37
Ah, I think I'm starting to understand.

You would like be able to set recurring transaction that will start at future without it appearing in transactions

Is that correct?

**Comment by shinebrillant** [comment] 2024-11-11 12:15
Yes.

If this month is November.
There are projects expected to be traded in November and December.
I only see this month's section in the trading items.

**Comment by vincius0000** [comment] 2024-11-11 15:38
@shinebrillant Do you mean that if this is made:

![image](https://github.com/user-attachments/assets/19327bf2-36db-4b41-8a73-4eb890e4fa97)

Then transactions should be like:

![image](https://github.com/user-attachments/assets/9a0b99ba-3fc3-44dd-8b20-cce857a8aadf)

But not:

![image](https://github.com/user-attachments/assets/b9741440-1c69-4033-a135-d1c320483873)

?

**Comment by vincius0000** [comment] 2024-11-11 15:58
@enrique-lozano I pass the microphone over to you.

I personally think that the current design of app does not allow this. Making something like that would be a bit difficult because it's an infinite number of transactions that we're talking about. When the page opens we also see future transactions right away, that means upon opening the page we would see year 9999 and then we would have to scroll down to see current time.

I hope you see what I mean. I do believe it's possible to do what you're looking for, but that would take some effort and that would be a feature request. Correct me if I'm wrong, Enrique.

**Comment by shinebrillant** [comment] 2024-11-11 16:08
> @enrique-lozano I pass the microphone over to you.
> 
> When the page opens we also see future transactions right away, that means upon opening the page we would see year 9999 and then we would have to scroll down to see current time.

It is not reasonable at all to need to scroll to find the current item, because it can be solved by just applying filtering. You can follow the month of the dashboard and customize it yourself in the transaction items.

![Screenshot_20241110-160108](https://github.com/user-attachments/assets/2a045f8e-eb65-46ea-9a59-7d8d6462583c)

**Comment by enrique-lozano** [comment] 2024-11-11 19:18
I'm going to try to shed some light on this, because I think that concepts are being mixed up in this issue. I will try to explain myself as brief as possible.

I wanted to start by mentioning that to display the transactions page, we have two ways that currently predominate in the market:

1 - Showing a navigation bar (positioned above or below the screen) so that we can go from one time period to the next or previous one, thus seeing the transactions of each period individually. Normally this is done by month (sometimes the app gives the option to change the periodicity and sometimes not)

As an example you can see apps like [Money Lover](https://play.google.com/store/apps/details?id=com.bookmark.money) or [Wallet by budgetBakers](https://play.google.com/store/apps/details?id=com.droid4you.application.wallet).

2 - Showing all the transactions directly at once using an infinity scroll. This is what Monekin currently does and what real bank apps such as BBVA, Santander or [Revolut](https://play.google.com/store/apps/details?id=com.revolut.revolut) usually do. For me, the latter is the one that implements this best by far.

In this app, the latter option was chosen because you can always set filters to go to the date you want quickly, instead of browsing through the menu. However, I think that both options are perfectly valid and I still have a hard time deciding which of the two is better. Either way, I don't plan to change anything about this decision right now due to lack of time.

With either of these two options we have the problem that @vincius0000 mentioned. If we have many pending transactions, we would have to scroll a lot to see the transactions that might really interest us. This problem occurs especially if we set small periodicities (transactions that are repeated every day or every week). In fact, it is something that currently occurs in many personal finance apps, for example in Wallet by budgetBakers it happens (screenshot in Spanish, sorry):

![Screenshot_20241111-190728](https://github.com/user-attachments/assets/61c20563-5aae-41fa-b1be-e587027318da)

With this I want to make it clear that unless someone comes up with a magic solution that I have not seen in any app, there is no perfect solution to this.

After a long investigation, I think that without a doubt the solution that I like the most and that is not so different from how Monekin is now is the solution that is given in 1Money:

![Screenshot_20241111-200130](https://github.com/user-attachments/assets/5e79dbba-3ef3-496f-93e0-540e34c563ae)

Here, future transactions are shown in a kind of separate section, and only the most recent transaction of the recurrence is shown. In case there are more transactions, it indicates how many there are. I think that this is the ideal solution and where our app should be heading in the next release. 

Please tell me what you think about all these @shinebrillant @vincius0000

**Comment by vincius0000** [comment] 2024-11-11 19:48
@enrique-lozano You've described everything very clearly.

I do like the concept of separate section for upcoming recurrent transactions. What's especially good is that you're not forced to see upcoming transactions as you have to expand the section to see them.

It's probably good as well that you only see nearest recurring transaction (for every recurring transaction you specify) as then it doesn't clutter the list. Although it is possible to see all recurrences, but then instead of fetching transactions from db, you actually dynamically create such recurring transactions. If you were to interact with transaction far far into future, then all occurrences up to that point would be written into db as pending. (Hopefully you see what I mean, it's one solution of doing it.)

Apart from that, when I go to recurring transactions page, it very nicely shows when is the next upcoming recurring transaction, so I already have the tool to forsee the expense. One thing that could aid me more is if I could opt in for notifications which would alert me that I will have "this" transaction this month, but this is another feature.

Coming back to what Enrique wrote, it all makes sense on why Monekin is designed as it is now.

**Comment by enrique-lozano** [comment] 2024-11-11 19:58
Yep, agree with all that @vincius0000. Regarding the notifications, we don't support any kind of notification right now in the app, but this will be a great feature to have in the future :)

**Comment by shinebrillant** [comment] 2024-11-12 12:21
I understand what you are saying. I will need a function. After I set the filter range in transaction items, I can maintain the function of the range I set after closing and reopening Monekin.

Transparency for transactions that are yet to come looks great.

**Comment by enrique-lozano** [comment] 2024-11-12 14:03
Okay, so I will close this issue to create a new one covering these new features. 

Please bear in mind that the discussions section should be used to talk about improvements/enhancements. Let's leave this section for the confirmed enhancements that will be implemented or for bugs

**Closed by enrique-lozano** 2024-11-12 14:03 UTC
Labels: type: bug, status: needs info
